baseURL = ""
title = "PKB-theme Example Site"
languageCode = "en-us"

# Enable features
enableGitInfo = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = 'github.com/stradichenko/PKB-theme'

  # Layouts from parent theme
  [[module.mounts]]
    source = "../layouts"
    target = "layouts"

  # Content mount 
  [[module.mounts]]
    source = "../content"
    target = "content"

  # Static assets
  [[module.mounts]]
    source = "../static"
    target = "static"

  # Static assets (pointing to parent theme's static folder)
  [[module.mounts]]
    source = "../static"    # Points to the theme's static folder
    target = "static"       # Mounts in the site's static directory

  # Assets pipeline
  [[module.mounts]]
    source = "../assets"
    target = "assets"

