baseURL = "https://stradichenko.github.io/PKB-theme/" #Theme's demo site
title = "PKB-theme Example Site"
languageCode = "en-us"

# Enable features
enableGitInfo = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

baseURL = "http://example.org/"
title = "My New Hugo Site"


