baseURL      = "https://stradichenko.github.io/PKB-theme/"
languageCode = "en-us"
title        = "PKB Theme Example"

# Essential for search functionality
[outputs]
  home = ['html', 'rss', 'json']
  page = ['html']
  section = ['html', 'rss']

[params]
  mainSections = ["posts", "docs"]

[module]
  [[module.imports]]
    path = "github.com/stradichenko/PKB-theme"

    [[module.imports.mounts]]
      source = "static" # inside the theme repo
      target = "static" # inject it into my site’s    

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "content"
      target = "content"

    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"