# Main Menu
[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 30

[[main]]
  name = "About"
  url = "/about/"
  weight = 40
 1