name: Build and Deploy ExampleSite to GitHub Pages

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128.0'
          extended: true

      - name: Cache Hugo modules & vendor
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            exampleSite/resources
            exampleSite/vendor
          key: ${{ runner.os }}-hugo

      - name: Reset & initialize Hugo module
        run: |
          cd exampleSite
          # Remove any existing Go module files
          rm -f go.mod go.sum
          # 1) Declare this directory as its own module again:
          hugo mod init github.com/stradichenko/PKB-theme/exampleSite
          # 2) Tell Go to require your theme (at v0.0.1, or whatever tag):
          go mod edit -require=github.com/stradichenko/PKB-theme@latest
          # 3) …but point that import back to the local parent directory:
          go mod edit -replace=github.com/stradichenko/PKB-theme=../

      - name: Install Hugo modules and vendor theme
        run: |
          cd exampleSite
          hugo mod tidy
          hugo mod vendor

      - name: Build example site
        run: |
          cd exampleSite
          hugo --minify --cleanDestinationDir --environment _default --logLevel debug

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: exampleSite/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
