name: Test Hugo Theme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        hugo-version: ['0.123.7'] # Match your theme's requirement

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: true

    - name: Install htmltest
      run: |
        # Fetch the latest version of htmltest
        # Fetch the latest version of htmltest, a tool for testing HTML output
        # It ensures that the generated site does not contain broken links or other HTML issues
        LATEST_VERSION=$(curl -s https://api.github.com/repos/wjdp/htmltest/releases/latest | grep "tag_name" | cut -d '"' -f 4)
        
        # Download the htmltest binary for the latest version
        wget -q https://github.com/wjdp/htmltest/releases/download/${LATEST_VERSION}/htmltest_${LATEST_VERSION}_linux_amd64.tar.gz || { echo "Error: Failed to download htmltest"; exit 1; }
          mv htmltest "$CACHE_DIR/htmltest_${LATEST_VERSION}"
        fi
        sudo cp "$CACHE_DIR/htmltest_${LATEST_VERSION}" /usr/local/bin/htmltest
        mv htmltest $HOME/bin/
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Build and test
      run: |
        cd exampleSite
        
        # Clean previous modules
        rm -rf go.mod go.sum resources/_gen public
        
        # Initialize temporary module
        hugo mod init temp-site
        
        # Get latest theme version automatically
        hugo mod get -u github.com/stradichenko/PKB-theme
        
        # Verify module integrity
        hugo mod verify
        
        # Build and test
        hugo --minify --cleanDestinationDir --environment production --logLevel debug
        htmltest -c .htmltest.yml --log-level info --skip-external
